# Aula 0

Nessa aula serão abordados alguns conceitos básicos de programação. Existem também diversas fontes de suporte disponíveis na internet como:<br/>
https://docs.python.org/3/tutorial/index.html (tutoriais oficiais)<br/> https://docs.python.org/3/library/index.html (referencia de funcoes oficial)<br/>
https://www.learnpython.org/ (tutorial interativo)<br/>
www.urionlinejudge.com.br (Exercíos e desafios)

## Variáveis
São entidades de programação que armazenam valores. Elas têm nome definido pelo usuário e o seu tipo depende de como ela é utilizada (o tipo é deduzido dinamicamente). Para declarar uma variável com nome X e que tenha o valor de 5 basta:

In [1]:
X = 5

Para saber o tipo de uma variável, podemos inspecionar seu tipo com a função $type$

In [2]:
type(X)

int

"int" quer dizer que o tipo é $integer$, ou seja, inteiro. Se quisermos que a variável aceite numeros reais, temos:

In [3]:
Y = 5.0
type(Y)

float

"float" quer dizer ponto flutuante. Eles podem representa números fracionários.


Podemos também forçar o tipo de uma variável

In [4]:
A = int(4)
B = int(5.3)
C = float(3)
D = float(4.3)
E = str('sou uma lista de caracteres')
F = str(5.35153)
print ('O valor de A eh: ' + str(A) + ' e seu tipo eh: ' + str(type(A)))
print ('O valor de B eh: ' + str(B) + ' e seu tipo eh: ' + str(type(B)) + 
       ' note que seu valor foi arredondado para o inteiro mais proximo')
print ('O valor de C eh: ' + str(C) + ' e seu tipo eh: ' + str(type(C)))
print ('O valor de D eh: ' + str(D) + ' e seu tipo eh: ' + str(type(D)))
print ('O valor de D eh: ' + str(E) + ' e seu tipo eh: ' + str(type(E)))
print ('O valor de D eh: ' + str(F) + ' e seu tipo eh: ' + str(type(F)))

O valor de A eh: 4 e seu tipo eh: <class 'int'>
O valor de B eh: 5 e seu tipo eh: <class 'int'> note que seu valor foi arredondado para o inteiro mais proximo
O valor de C eh: 3.0 e seu tipo eh: <class 'float'>
O valor de D eh: 4.3 e seu tipo eh: <class 'float'>
O valor de D eh: sou uma lista de caracteres e seu tipo eh: <class 'str'>
O valor de D eh: 5.35153 e seu tipo eh: <class 'str'>


 Também podemos representar números complexos:

In [5]:
num = complex('4+3j')
print (num)

(4+3j)


Representamos um número complexo com parte real igual a 4 e parte imaginária igual a 3, sendo "j" variável complexa $\sqrt(-1)$. 

### Operações Básicas
Podemos realizar operações algébricas e lógicas sobre as variáveis.

In [6]:
A = 5+2 # soma
B = 5-2 # subtracao
C = 5*2 # multiplicacao
D = 5/2 # divisao
E = 5%2 # resto
G = 5**2# exponencial. CUIDADO: 5^2 em python significa a operação binário XOR, e não exponencial

Operações de comparação:

In [7]:
print(A == B) # igualdade (note que o = serve para atribuir valores)
print(A != B) # nao igual
print(A > B)  # maior
print(A < B)  # menor
print(A >= B) # maior igual
print(A <= B) # menor igual

False
True
True
False
True
False


Os valores True e False acima são resultado das operações de comparação com base nos valores de A e B definidos anteriormente.

Também são suportadas operações de lógica booleana.

In [8]:
A = True
B = False
print(A and B)
print(A and not B)
print(A or B)

False
True
True


Para mais informações sobre operadores veja o link: https://www.tutorialspoint.com/python/python_basic_operators.htm

### Containers
Python suporta diversas estruturas para armazenamento de variáveis de forma estruturada. A mais comum é a lista, que pode ser definida das seguintes formas:

In [9]:
lista = list([1,2,3,47,3]) # com o comando list explicito
lista2 = [1,4214,1242,124,6] # forma implicita do comando

In [10]:
print('A lista contem ' + str(len(lista)) + ' elementos, sendo eles: ' + str(lista))
print('O primeiro item da lista e ' + str(lista[0]) + ' e o ultimo e: ' + str(lista[-1]))

A lista contem 5 elementos, sendo eles: [1, 2, 3, 47, 3]
O primeiro item da lista e 1 e o ultimo e: 3


In [11]:
lista[3] = 77 # modifica o elemento na posicao 3 (o quarto elemento a partir do 0)
print('O quarto elemento foi modificado para: ' + str(lista[3]))

lista.append(99) # insere um elemento no fim da lista
print('O novo ultimo elemento agora e: '+ str(lista[-1]))

lista.insert(2, 101) # insere o valor 101 na posicao 2
print('A lista agora tem os seguintes valores: ' + str(lista))

O quarto elemento foi modificado para: 77
O novo ultimo elemento agora e: 99
A lista agora tem os seguintes valores: [1, 2, 101, 3, 77, 3, 99]


Também podemos criar listas que não podem ser modificadas. São chamadas de tuplas. São úteis para quando queremos garantir que a estrutura não será modificada.

In [12]:
tupla = (32,1,23,4)
#tupla[2] = 7  # essa linha causaria um erro

É considerado boa prática utilizar listas para itens de mesmo tipo e tuplas para conjuntos heterogêneos.

In [13]:
dia = (25, 'janeiro', 2018)

### Vetores e matrizes
Podemos tentar representar vetores e matrizes com listas. Por exemplo:

In [14]:
A = [1,2,3,4]
B = [1,2,3,4]
print(A+B)

[1, 2, 3, 4, 1, 2, 3, 4]


Vemos que listas não se comportam da forma que esperamos para vetores. Ao invés de somar os vetores elemento a elemento, o Python concatena as duas listas. Vamos tentar multiplicar por um valor escalar:

In [15]:
print(A*3)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


Novamente, o comportamento esperado não foi obtido, o Python simplesmente replicou a lista 3 vezes. 

As noções matemáticas de vetores e matrizes não são suportados nativamente pelo Python. Então precisamos, ou programar para que o Python faça o esperado, ou simplesmente importar estruturas de dados para os vetores e matrizes de algum lugar externo, chamado biblioteca em programação. No Python, a maneira de trazer componentes externos é através de comandos $import$:

In [16]:
import numpy as np

Esse comando importa a biblioteca Numpy, que define estrutura de matrizes e vetores, e a inclui em nosso programa com o nome "np". Para definirmos um vetor agora podemos simplesmente:

In [17]:
vetorlin = np.array([1,2,3,4]) # Vetor linha: 1 linha e 4 colunas
print(vetorlin)

[1 2 3 4]


Repare que a função $array$ recebe uma lista de números e cria uma matriz ou vetor. Para o caso de vetorlin, onde temos uma linha, utilizamos apenas uma lista.

 Para criar uma matriz com mais de uma linha, devemos fornecer múltiplas listas para a função $array$. Por exemplo, para criar o vetor $vetorlin^T$, devemos passar 4 listas com um elemento em casa. Repare que o conjunto de listas deve estar contido dentro de uma tupla (por isso temos dois parêntesis de cada lado):  

In [18]:
vetorcol = np.array(([1],[2],[3],[4])) # Vetor coluna: 4 linhas e 1 coluna
print(vetorcol)

[[1]
 [2]
 [3]
 [4]]


E para o caso de uma matriz:

In [19]:
matriz = np.array(([1,2,3,4],[5,6,7,8])) # Matrix 2x4: 2 linhas e 4 colunas
print(matriz)

[[1 2 3 4]
 [5 6 7 8]]


In [20]:
print('O vetor linha tem dimensao ' + str(vetorlin.shape) +' e tipo '+ str(vetorlin.dtype))

O vetor linha tem dimensao (4,) e tipo int64


Repare que o atributo $shape$ referente a variável $vetor$ é uma tupla onde o primeiro elemento é o número de linhas e o segundo o de colunas (como tem apenas 1 coluna, o parâmetro é omitido). O tipo $int64$ quer dizer que é um número inteiro representado utilizando 64 bits.

In [21]:
print('O item na posicao linha,coluna:1,3 na matriz eh: ' + str(matriz[1,3]))

O item na posicao linha,coluna:1,3 na matriz eh: 8


Listas, tuplas, matrizes e todas as outras estruturas com diversos valores são indexadas a partir do 0.

Quando matrizes têm o mesmo número de elementos, elas também suportam operações algébricas e lógicas:

In [22]:
A = np.array(([1,2],[3,4]))
B = np.array(([4,3],[2,1]))
print(A)

print(B)

[[1 2]
 [3 4]]
[[4 3]
 [2 1]]


Confira agora se as matrizes A e B se comportam como o esperado. Pesquise também como realizar a operação de produto escalar utilizando a biblioteca Numpy (em inglês produto escalar é dot product).

## Loops

Programas geralmente fazem um grande número de operações repetitivas em grandes conjuntos de dados. Por exemplo, se quisermos imprimir todos os elementos da variável "lista", temos que:

In [23]:
print(lista[0])
print(lista[1])
print(lista[2])
print(lista[3])
print(lista[4])
print(lista[5])

1
2
101
3
77
3


Para evitarmos repetir código (e se essa lista tivesse mil elementos???) utilizamos estruturas de loop. Sua estrutura é:

In [24]:
for elemento in lista:
    print(elemento)

1
2
101
3
77
3
99


De forma similar, podemos obter o indice e elemento atuais para cada "rodada" do loop através da função $enumerate$.

In [25]:
for indice, elemento in enumerate(lista):
    print('O elemento na posicao ' + str(indice) + ' tem valor: ' + str(elemento))

O elemento na posicao 0 tem valor: 1
O elemento na posicao 1 tem valor: 2
O elemento na posicao 2 tem valor: 101
O elemento na posicao 3 tem valor: 3
O elemento na posicao 4 tem valor: 77
O elemento na posicao 5 tem valor: 3
O elemento na posicao 6 tem valor: 99


Podemos utilizar loops para realizar operações que dependem de todos os elementos de uma lista. Por exemplo somar todos os itens em uma lista:

In [26]:
soma = 0
for elemento in lista:
    soma = soma + elemento
print(soma)

286


## Condicionais
Também podemos executar um certo trecho de código apenas se uma condição for atendida:

In [27]:
if (matriz[1,1] > 3):
    print('O valor ' + str(matriz[1,1]) + ' eh maior que 3')
elif (matriz[1,1] < 3):
    print('O valor ' + str(matriz[1,1]) + ' eh menor que 3')
else:
    print('O valor ' + str(matriz[1,1]) + ' soh pode ser 3')

O valor 6 eh maior que 3


## Funções
É comum querermos utilizar uma mesma funcionalidade em diversos pontos do código. Funções permitem que isso aconteça. Elas são entidades que recebem um conjunto de dados ou parâmetros de entrada e retorna zero ou mais valores de saída. Por exemplo a função $print$ que temos utilizado recebe um vetor de caracteres de entrada e sua saída é texto formatado na tela. 

Para se definir uma função basta:

In [28]:
def soma(parametro1, parametro2, parametro3):
    # Faz alguma coisa com os parametros
    return parametro1+parametro2+parametro3

A função acima realiza a soma de 3 paramâmetros. Para usá-la:

In [29]:
print(soma(3,5,6))

14


## Exercício 1
Faça uma função que calcula seu RSG para um dado semestre. A função deve receber valores de crédito e nota final correspondentes e retornar um valor de RSG de 0 a 5. Considere que o semestre terá apenas 3 disciplinas. Dica: crie primeiro uma função que recebe uma nota de 0 a 100 e gera um conceito (use 5 para A, 4 para B e assim por diante).


## Exercício 2 
Adapte a função do Ex. 1 para aceitar como entrada um número qualquer de disciplinas. Dica: você pode passar uma matriz onde cada linha representa uma disciplina, a primeira coluna representa o número de créditos e a segunda coluna representa a nota final. Você também pode passar uma lista de número de créditos e outra lista com as notas.

Abaixo listas de notas e créditos para testar suas funções:

Notas = 90, 50, 40, 30

Creditos = 12, 8, 6, 4

RSG = 2.2666
-----------------
Notas = 43

Creditos = 4

RSG = 0
-----------------
Notas = 100, 98, 97, 95, 94, 80, 74, 68, 49

Créditos = 1, 4, 6, 8, 12, 3, 6, 8, 12

RSG = 3.35
----------------
Notas = 91, 90, 89

Créditos = 1,2,3

RSG = 4.5
---------------